### ISSUE TITLE
Check for R architectures requires default install folder

### ISSUE THREAD

**Issue by schuemie** [ablack3/HadesPrerequisites#1]
The current check for which R versions are installed assumed R is installed in the default location, but this needn't be true. (In fact, I [recommend](https://ohdsi.github.io/Hades/rSetup.html) people not to).

An alternative way would be to see which subfolders exist in R's bin folder. The list of files can obtained using

```r
list.files(dirname(R.home("bin")), include.dirs = TRUE)
```

I see the 64-bit version is in a subfolder named 'x64', I'm not sure what is used for the 32-bit version. Probably if we grepl for '32' and '64' we'll be fine.

**Comment by ablack3** [comment]
Thanks for this suggestion. I still need to add the check for mac OS and Linux but Windows should be good.
