### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by schuemie** [ablack3/HadesPrerequisites#2]
I'm sorry to have to ask this, but better early than later: would you mind adhering to the [HADES code style](https://ohdsi.github.io/Hades/codeStyle.html)? Specifically, use camelCase instead of snake_case?

**Comment by ablack3** [comment]
Yes of course. I've been using snake case out of habit but definitely want my contributions to conform to the OHDSI style. Is there an OHDSI R style guide? If not that might be something to put on the OHDSI-R  roadmap.

**Comment by schuemie** [comment]
Yes, the HADES R style guide is the OHDSI R style guide: https://ohdsi.github.io/Hades/codeStyle.html

**Comment by ablack3** [comment]
Of course. I should have found that! Thanks.
